restore ability to remove cents from amounts
artsy/money_helper pull request #27
Opened 2021-10-15 22:12 UTC by agrberg

I wasn't able to find an explicit reason to remove this feature when making the breaking change in https://github.com/artsy/money_helper/pull/20 so I'm adding it back as another library depends on the `no_cents` option to `Money#format`.

2021-10-17 19:29 UTC, dblock requested changes

2021-10-17 19:29 UTC, dblock commented on CHANGELOG.md
> -* Your contribution here.
Put this back?

2021-10-17 19:29 UTC, dblock commented on lib/money_helper.rb
> +  def self.money_to_text(amount_minor, currency: 'USD', with_currency: true, with_symbol: true, money_format: {})
This makes this method a hybrid where some options are passed as fields and others are passed as a hash, which feels like the worst of both worlds. I think I would prefer if we either incremented the major version, and made a backward incompatible change making a single `options = { format: symbol: }` parameter. If you don't want to make the change, I would explicitly add any option(s) such as `no_cents` that you need.

2021-10-17 21:19 UTC, agrberg commented on lib/money_helper.rb
> +  def self.money_to_text(amount_minor, currency: 'USD', with_currency: true, with_symbol: true, money_format: {})
I think it's the better move for the long run, I didn't want to force another breaking change so soon but if you're onboard then let's do it :shipit:

2021-12-23 22:36 UTC, dblock commented
I missed this for some reason (GH notifications 😠 ), sorry about that. 

Update README and I can merge?

2022-01-03 22:41 UTC, agrberg commented
@dblock added `UPGRADEING.md` as requested and broke out the 3.0.0 changes from the 2.0.0 changes for easier visibility.

Happy to help with this gem as well. I'm also a minor co-maintainer on your https://github.com/dblock/iex-ruby-client/ gem as well 🙌 

For whatever reason I still cannot request a re-review so I'll be emailing you as well.

2022-01-06 18:03 UTC, joeyAghion commented
@dblock you're in!

@agrberg thanks for the contribution. Glad to see that the library is useful for you.

2022-01-06 18:04 UTC, merged

2022-01-06 18:30 UTC, dblock commented
Can we add @agrberg as a co-maintainer and give him rubygems access to make a release?

2022-02-16 23:45 UTC, annacarey commented
@agrberg we ended up needing your changes for something at Artsy so I released the new version. Thank you so much for your contributions here!